name: cartracker
description: GPS car tracker

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.2
  mapbox_gl: 0.14.0
  uuid: 3.0.5
  sqflite: 2.0.1
  fluttercontactpicker: 4.6.0
  path: 1.8.0
  path_provider: 2.0.8
  provider: 6.0.2
  telephony: 0.1.4
  flutter_colorpicker: 1.0.3
  image_picker: 0.8.4+4
  fluttertoast: 8.0.8
  flutter_slidable: 1.2.0
  url_launcher: 6.0.18
  geolocator: 8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sdf/
